# -*- coding: utf-8 -*-
"""HM4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WrtnSIALdGP9c8OyqXwnMGETiKHI5WYq

# Home 4: Build a CNN for image recognition.

### Name: [Tianyi Li]

## 0. You will do the following:

1. Read, complete, and run the code.

2. **Make substantial improvements** to maximize the accurcy.
    
3. Convert the .IPYNB file to .HTML file.

    * The HTML file must contain the code and the output after execution.
    
    * Missing **the output after execution** will not be graded.
    
4. Upload this .HTML file to your Google Drive, Dropbox, or Github repo. (If you submit the file to Google Drive or Dropbox, you must make the file "open-access". The delay caused by "deny of access" may result in late penalty.)

4. Submit the link to this .HTML file to Canvas.

    * Example: https://github.com/wangshusen/CS583-2020S/blob/master/homework/HM4/HM4.html


## Requirements:

1. You can use whatever CNN architecture, including VGG, Inception, and ResNet. However, you must build the networks layer by layer. You must NOT import the archetectures from ```keras.applications```.

2. Make sure ```BatchNormalization``` is between a ```Conv```/```Dense``` layer and an ```activation``` layer.

3. If you want to regularize a ```Conv```/```Dense``` layer, you should place a ```Dropout``` layer **before** the ```Conv```/```Dense``` layer.

4. An accuracy above 70% is considered reasonable. An accuracy above 80% is considered good. Without data augmentation, achieving 80% accuracy is difficult.


## Google Colab

- If you do not have GPU, the training of a CNN can be slow. Google Colab is a good option.

- Keep in mind that you must download it as an IPYNB file and then use IPython Notebook to convert it to HTML.

- Also keep in mind that the IPYNB and HTML files must contain the outputs. (Otherwise, the instructor will not be able to know the correctness and performance.) Do the followings to keep the outputs.

- In Colab, go to ```Runtime``` --> ```Change runtime type``` --> Do NOT check ```Omit code cell output when saving this notebook```. In this way, the downloaded IPYNB file contains the outputs.

## 1. Data preparation

### 1.1. Load data
"""

from keras.datasets import cifar10
import numpy

(x_train, y_train), (x_test, y_test) = cifar10.load_data()

print('shape of x_train: ' + str(x_train.shape))
print('shape of y_train: ' + str(y_train.shape))
print('shape of x_test: ' + str(x_test.shape))
print('shape of y_test: ' + str(y_test.shape))
print('number of classes: ' + str(numpy.max(y_train) - numpy.min(y_train) + 1))

"""### 1.2. One-hot encode the labels

In the input, a label is a scalar in $\{0, 1, \cdots , 9\}$. One-hot encode transform such a scalar to a $10$-dim vector. E.g., a scalar ```y_train[j]=3``` is transformed to the vector ```y_train_vec[j]=[0, 0, 0, 1, 0, 0, 0, 0, 0, 0]```.

1. Define a function ```to_one_hot``` that transforms an $n\times 1$ array to a $n\times 10$ matrix.

2. Apply the function to ```y_train``` and ```y_test```.
"""

import numpy as np

def to_one_hot(y, num_class=10):
  #<fill the function>
  results = np.zeros((len(y), num_class))
  for i, y in enumerate(y):
    results[i, y] = 1
  return results

y_train_vec = to_one_hot(y_train)
y_test_vec = to_one_hot(y_test)

print('Shape of y_train_vec: ' + str(y_train_vec.shape))
print('Shape of y_test_vec: ' + str(y_test_vec.shape))

print(y_train[0])
print(y_train_vec[0])

"""#### Remark: the outputs should be
* Shape of y_train_vec: (50000, 10)
* Shape of y_test_vec: (10000, 10)
* [6]
* [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]

### 1.3. Randomly partition the training set to training and validation sets

Randomly partition the 50K training samples to 2 sets:
* a training set containing 40K samples
* a validation set containing 10K samples
"""

rand_indices = numpy.random.permutation(50000)
train_indices = rand_indices[0:40000]
valid_indices = rand_indices[40000:50000]

x_val = x_train[valid_indices, :]
y_val = y_train_vec[valid_indices, :]

x_tr = x_train[train_indices, :]
y_tr = y_train_vec[train_indices, :]

print('Shape of x_tr: ' + str(x_tr.shape))
print('Shape of y_tr: ' + str(y_tr.shape))
print('Shape of x_val: ' + str(x_val.shape))
print('Shape of y_val: ' + str(y_val.shape))

"""## 2. Build a CNN and tune its hyper-parameters

1. Build a convolutional neural network model
2. Use the validation data to tune the hyper-parameters (e.g., network structure, and optimization algorithm)
    * Do NOT use test data for hyper-parameter tuning!!!
3. Try to achieve a validation accuracy as high as possible.

### Remark: 

The following CNN is just an example. You are supposed to make **substantial improvements** such as:
* Add more layers.
* Use regularizations, e.g., dropout.
* Use batch normalization.
"""

from keras.layers import *
from keras.models import Model,Sequential

# network structure 1(showing better performance in tuning): simple ResNet-like network
def CNNModel1():
  inputx = Input(shape=(32, 32, 3))
  # block_1
  layer = Conv2D(64, (3, 3),padding='same')(inputx)
  layer = BatchNormalization()(layer)
  layer = Activation('relu')(layer)
  layer = Conv2D(64, (7, 7),padding='same')(layer)
  layer = BatchNormalization()(layer)
  layer = Activation('relu')(layer)
  block_1_output = MaxPooling2D((2, 2))(layer)
  # block_2
  layer = Dropout(0.5)(block_1_output)
  layer = Conv2D(64, (3, 3),padding='same')(layer)
  layer = BatchNormalization()(layer)
  layer = Activation('relu')(layer)
  layer = Conv2D(64, (7, 7),padding='same')(layer)
  layer = BatchNormalization()(layer)
  layer = Activation('relu')(layer)
  block_2_output = add([layer, block_1_output])
  # last
  layer = Flatten()(block_2_output)
  layer = Dropout(0.5)(layer)
  layer = Dense(128)(layer)
  layer = BatchNormalization()(layer)
  layer = Activation('relu')(layer)
  outputx = Dense(10, activation='softmax')(layer)
  model = Model(inputx, outputx)

  return model

# network structure 2: modified on original code
def CNNModel2():
  model = Sequential()
  model.add(Conv2D(32, (3, 3),padding='same', input_shape=(32, 32, 3))) # add
  model.add(BatchNormalization()) # add
  model.add(Activation('relu')) # add
  model.add(MaxPooling2D((2, 2)))

  model.add(Conv2D(64, (3, 3),padding='same'))  # add
  model.add(BatchNormalization()) # add
  model.add(Activation('relu')) # add
  model.add(MaxPooling2D((2, 2)))

  model.add(Conv2D(64, (3, 3),padding='same'))  # add
  model.add(BatchNormalization()) # add
  model.add(Activation('relu')) # add
  model.add(MaxPooling2D((2, 2)))

  model.add(Flatten())
  model.add(Dropout(0.5)) # add
  model.add(Dense(128))
  model.add(BatchNormalization()) # add
  model.add(Activation('relu')) # add
  model.add(Dense(10, activation='softmax'))

  return model

model = CNNModel1()
model.summary()
model = CNNModel2()
model.summary()

# Commented out IPython magic to ensure Python compatibility.
# tune its hyper-parameters: learning_rate, CNN structure

from keras import optimizers
import matplotlib.pyplot as plt
# %matplotlib inline

learning_rate = [1E-5, 1E-4, 3E-4, 1E-3] # to be tuned!

for i in learning_rate:
  print('When learning_rate = %f:'%i)
  for fn in [CNNModel1, CNNModel2]:
    # fit
    print('  When mode is %s:'%(fn.__name__))
    model = fn()
    model.compile(loss='categorical_crossentropy',
                  optimizer=optimizers.RMSprop(lr=i),
                  metrics=['acc'])
    history = model.fit(x_tr, y_tr, batch_size=32, epochs=20, validation_data=(x_val, y_val))

    # plot
    acc = history.history['acc']
    val_acc = history.history['val_acc']
    epochs = range(len(acc))
    plt.plot(epochs, acc, 'bo', label='Training acc')
    plt.plot(epochs, val_acc, 'r', label='Validation acc')
    plt.xlabel('Epochs')
    plt.ylabel('Accuracy')
    plt.legend()
    plt.show()

"""## 3. Train (again) and evaluate the model

- To this end, you have found the "best" hyper-parameters. 
- Now, fix the hyper-parameters and train the network on the entire training set (all the 50K training samples)
- Evaluate your model on the test set.

### 3.1. Train the model on the entire training set

Why? Previously, you used 40K samples for training; you wasted 10K samples for the sake of hyper-parameter tuning. Now you already know the hyper-parameters, so why not using all the 50K samples for training?
"""

# choose the best hyper-paras
learning_rate = 3E-4
model = CNNModel1()

# compile
model.compile(loss='categorical_crossentropy',
              optimizer=optimizers.RMSprop(lr=learning_rate),
              metrics=['acc'])

# <Train your model on the entire training set (50K samples)>
# <Use (x_train, y_train_vec) instead of (x_tr, y_tr)>
# <Do NOT use the validation_data option (because now you do not have validation data)>
# ...

# training by all 50K samples
history = model.fit(x_train, y_train_vec, batch_size=32, epochs=80)

"""### 3.2. Evaluate the model on the test set

Do NOT used the test set until now. Make sure that your model parameters and hyper-parameters are independent of the test set.
"""

loss_and_acc = model.evaluate(x_test, y_test_vec)
print('loss = ' + str(loss_and_acc[0]))
print('accuracy = ' + str(loss_and_acc[1]))

